import { config } from 'dotenv'
import path from 'path'

config({
  path: path.join(__dirname, `../../.env.${process.env.NODE_ENV || 'dev'}`),
})

const {
  PORT,
  NODE_ENV,
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  JWKS_URI,
  PRIVATE_KEY,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  FRONTEND_CLIENT_UI,
  FRONTEND_ADMIN_UI,
  MAIN_DOMAIN,
} = process.env

export const Config = {
  PORT,
  NODE_ENV,
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  JWKS_URI,
  PRIVATE_KEY,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  FRONTEND_CLIENT_UI,
  FRONTEND_ADMIN_UI,
  MAIN_DOMAIN,
}
